#############################################################################
# Makefile for building: bin/trinchete
# Generated by qmake (3.1) (Qt 5.15.11)
# Project:  trinchete.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile trinchete.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -Ibuild/moc -I/usr/lib/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = trinchete1.0.0
DISTDIR = /home/void/2.0/build/obj/trinchete1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib
LIBS          = $(SUBLIBS) /usr/lib/libQt5Widgets.so /usr/lib/libQt5Gui.so /usr/lib/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = build/obj/

####### Files

SOURCES       = src/main.cpp \
		src/core/version_manager.cpp \
		src/core/game_launcher.cpp \
		src/core/version_config.cpp \
		src/ui/windows/launcher_window.cpp \
		src/ui/dialogs/extract_dialog.cpp build/rcc/qrc_resources.cpp \
		build/moc/moc_version_manager.cpp \
		build/moc/moc_game_launcher.cpp \
		build/moc/moc_version_config.cpp \
		build/moc/moc_launcher_window.cpp \
		build/moc/moc_extract_dialog.cpp
OBJECTS       = build/obj/main.o \
		build/obj/version_manager.o \
		build/obj/game_launcher.o \
		build/obj/version_config.o \
		build/obj/launcher_window.o \
		build/obj/extract_dialog.o \
		build/obj/qrc_resources.o \
		build/obj/moc_version_manager.o \
		build/obj/moc_game_launcher.o \
		build/obj/moc_version_config.o \
		build/obj/moc_launcher_window.o \
		build/obj/moc_extract_dialog.o
DIST          = /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		trinchete.pro src/core/version_manager.h \
		src/core/game_launcher.h \
		src/core/version_config.h \
		src/ui/windows/launcher_window.h \
		src/ui/dialogs/extract_dialog.h src/main.cpp \
		src/core/version_manager.cpp \
		src/core/game_launcher.cpp \
		src/core/version_config.cpp \
		src/ui/windows/launcher_window.cpp \
		src/ui/dialogs/extract_dialog.cpp
QMAKE_TARGET  = trinchete
DESTDIR       = bin/
TARGET        = bin/trinchete


first: all
####### Build rules

bin/trinchete:  $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: trinchete.pro /usr/lib/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/qt5/mkspecs/common/unix.conf \
		/usr/lib/qt5/mkspecs/common/linux.conf \
		/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/qt5/mkspecs/qconfig.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/qt5/mkspecs/features/default_post.prf \
		/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/qt5/mkspecs/features/qt.prf \
		/usr/lib/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/qt5/mkspecs/features/resources.prf \
		/usr/lib/qt5/mkspecs/features/moc.prf \
		/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt5/mkspecs/features/uic.prf \
		/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/qt5/mkspecs/features/yacc.prf \
		/usr/lib/qt5/mkspecs/features/lex.prf \
		trinchete.pro \
		resources/resources.qrc
	$(QMAKE) -o Makefile trinchete.pro
/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/qt5/mkspecs/common/unix.conf:
/usr/lib/qt5/mkspecs/common/linux.conf:
/usr/lib/qt5/mkspecs/common/sanitize.conf:
/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt5/mkspecs/common/g++-base.conf:
/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/qt5/mkspecs/qconfig.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/qt5/mkspecs/features/qt_config.prf:
/usr/lib/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt5/mkspecs/features/toolchain.prf:
/usr/lib/qt5/mkspecs/features/default_pre.prf:
/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/qt5/mkspecs/features/default_post.prf:
/usr/lib/qt5/mkspecs/features/warn_on.prf:
/usr/lib/qt5/mkspecs/features/qt.prf:
/usr/lib/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/qt5/mkspecs/features/resources.prf:
/usr/lib/qt5/mkspecs/features/moc.prf:
/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/qt5/mkspecs/features/uic.prf:
/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/qt5/mkspecs/features/file_copies.prf:
/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/qt5/mkspecs/features/exceptions.prf:
/usr/lib/qt5/mkspecs/features/yacc.prf:
/usr/lib/qt5/mkspecs/features/lex.prf:
trinchete.pro:
resources/resources.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile trinchete.pro

qmake_all: FORCE


all: Makefile bin/trinchete

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources/resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/core/version_manager.h src/core/game_launcher.h src/core/version_config.h src/ui/windows/launcher_window.h src/ui/dialogs/extract_dialog.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/core/version_manager.cpp src/core/game_launcher.cpp src/core/version_config.cpp src/ui/windows/launcher_window.cpp src/ui/dialogs/extract_dialog.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: build/rcc/qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/rcc/qrc_resources.cpp
build/rcc/qrc_resources.cpp: resources/resources.qrc \
		/usr/lib/qt5/bin/rcc \
		resources/icons8-minecraft-dirt-block-96.png \
		resources/icons8-minecraft-creeper-96.png \
		resources/trinihq_vector.png \
		resources/appicon.png
	/usr/lib/qt5/bin/rcc -name resources resources/resources.qrc -o build/rcc/qrc_resources.cpp

compiler_moc_predefs_make_all: build/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc/moc_predefs.h
build/moc/moc_predefs.h: /usr/lib/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -Wextra -dM -E -o build/moc/moc_predefs.h /usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc/moc_version_manager.cpp build/moc/moc_game_launcher.cpp build/moc/moc_version_config.cpp build/moc/moc_launcher_window.cpp build/moc/moc_extract_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc/moc_version_manager.cpp build/moc/moc_game_launcher.cpp build/moc/moc_version_config.cpp build/moc/moc_launcher_window.cpp build/moc/moc_extract_dialog.cpp
build/moc/moc_version_manager.cpp: src/core/version_manager.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/void/2.0/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/void/2.0 -I/home/void/2.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/14.2.1 -I/usr/include/c++/14.2.1/x86_64-unknown-linux-gnu -I/usr/include/c++/14.2.1/backward -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include-fixed -I/usr/include src/core/version_manager.h -o build/moc/moc_version_manager.cpp

build/moc/moc_game_launcher.cpp: src/core/game_launcher.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/void/2.0/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/void/2.0 -I/home/void/2.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/14.2.1 -I/usr/include/c++/14.2.1/x86_64-unknown-linux-gnu -I/usr/include/c++/14.2.1/backward -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include-fixed -I/usr/include src/core/game_launcher.h -o build/moc/moc_game_launcher.cpp

build/moc/moc_version_config.cpp: src/core/version_config.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/void/2.0/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/void/2.0 -I/home/void/2.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/14.2.1 -I/usr/include/c++/14.2.1/x86_64-unknown-linux-gnu -I/usr/include/c++/14.2.1/backward -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include-fixed -I/usr/include src/core/version_config.h -o build/moc/moc_version_config.cpp

build/moc/moc_launcher_window.cpp: src/ui/windows/launcher_window.h \
		src/core/version_config.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/void/2.0/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/void/2.0 -I/home/void/2.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/14.2.1 -I/usr/include/c++/14.2.1/x86_64-unknown-linux-gnu -I/usr/include/c++/14.2.1/backward -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include-fixed -I/usr/include src/ui/windows/launcher_window.h -o build/moc/moc_launcher_window.cpp

build/moc/moc_extract_dialog.cpp: src/ui/dialogs/extract_dialog.h \
		build/moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/void/2.0/build/moc/moc_predefs.h -I/usr/lib/qt5/mkspecs/linux-g++ -I/home/void/2.0 -I/home/void/2.0/src -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtCore -I/usr/include/c++/14.2.1 -I/usr/include/c++/14.2.1/x86_64-unknown-linux-gnu -I/usr/include/c++/14.2.1/backward -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include -I/usr/local/include -I/usr/lib64/gcc/x86_64-unknown-linux-gnu/14.2.1/include-fixed -I/usr/include src/ui/dialogs/extract_dialog.h -o build/moc/moc_extract_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

build/obj/main.o: src/main.cpp src/ui/windows/launcher_window.h \
		src/core/version_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/main.o src/main.cpp

build/obj/version_manager.o: src/core/version_manager.cpp src/core/version_manager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/version_manager.o src/core/version_manager.cpp

build/obj/game_launcher.o: src/core/game_launcher.cpp src/core/game_launcher.h \
		src/core/version_manager.h \
		src/core/version_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/game_launcher.o src/core/game_launcher.cpp

build/obj/version_config.o: src/core/version_config.cpp src/core/version_config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/version_config.o src/core/version_config.cpp

build/obj/launcher_window.o: src/ui/windows/launcher_window.cpp src/ui/windows/launcher_window.h \
		src/core/version_config.h \
		src/core/game_launcher.h \
		src/core/version_manager.h \
		src/ui/dialogs/extract_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/launcher_window.o src/ui/windows/launcher_window.cpp

build/obj/extract_dialog.o: src/ui/dialogs/extract_dialog.cpp src/ui/dialogs/extract_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/extract_dialog.o src/ui/dialogs/extract_dialog.cpp

build/obj/qrc_resources.o: build/rcc/qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/qrc_resources.o build/rcc/qrc_resources.cpp

build/obj/moc_version_manager.o: build/moc/moc_version_manager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_version_manager.o build/moc/moc_version_manager.cpp

build/obj/moc_game_launcher.o: build/moc/moc_game_launcher.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_game_launcher.o build/moc/moc_game_launcher.cpp

build/obj/moc_version_config.o: build/moc/moc_version_config.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_version_config.o build/moc/moc_version_config.cpp

build/obj/moc_launcher_window.o: build/moc/moc_launcher_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_launcher_window.o build/moc/moc_launcher_window.cpp

build/obj/moc_extract_dialog.o: build/moc/moc_extract_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/obj/moc_extract_dialog.o build/moc/moc_extract_dialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

