name: QT5 - SSE3 Compilar y Empaquetar AppImage

on:
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Trinity (Repositorio Principal)
        uses: actions/checkout@v4
        with:
          ref: 'qt5-up'
          path: 'trinity'

      - name: Clonar Dependencias Externas
        run: |
          git clone --recursive -b ng https://github.com/minecraft-linux/mcpelauncher-manifest.git mcpelauncher
          git clone --recursive https://github.com/minecraft-linux/msa-manifest.git msa
          git clone https://codeberg.org/javiercplus/mcpe-extract.git
          git clone https://github.com/minecraft-linux/mcpelauncher-linux-bin.git linux-bin

      - name: Instalar Dependencias del Sistema
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential git curl cmake clang ninja-build \
            qtbase5-dev qtbase5-dev-tools qtdeclarative5-dev qtwebengine5-dev libqt5svg5-dev qttools5-dev qttools5-dev-tools \
            libcurl4-openssl-dev libssl-dev libasound2-dev libpulse-dev libjack-jackd2-dev libpipewire-0.3-dev \
            libx11-dev libxi-dev libxext-dev libxfixes-dev libxcursor-dev libxrandr-dev libxss-dev libxtst-dev \
            libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libvulkan-dev vulkan-validationlayers \
            libdrm-dev libgbm-dev libudev-dev libevdev-dev libusb-1.0-0-dev libdbus-1-dev bluez \
            libibus-1.0-dev libxkbcommon-dev libpng-dev libzip-dev libcups2-dev libwayland-dev libunwind-dev libdecor-0-dev \
            file python3

      - name: Verificar libzip instalado
        run: |
          dpkg -l | grep libzip
          ls -la /usr/lib/x86_64-linux-gnu/libzip.so*

      - name: Compilar MCPE-Extract
        run: |
          cd mcpe-extract
          mkdir -p build
          cd build
          cmake .. -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_POLICY_VERSION_MINIMUM=3.5
          make -j$(nproc)

      - name: Compilar MSA (64 bits)
        run: |
          export CC=clang CXX=clang++
          cmake -S msa -B msa/build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_MSA_QT_UI=ON \
            -Wno-dev
          ninja -C msa/build

      - name: Compilar MCPELauncher (No GUI)
        run: |
          wget https://huggingface.co/datasets/ccoffee20/trinity-installer/resolve/main/patch.sh
          bash patch.sh
          export CC=clang CXX=clang++
          cmake -S mcpelauncher -B mcpelauncher/build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DBUILD_WEBVIEW=OFF \
            -DBUILD_UI=OFF \
            -Wno-dev
          ninja -C mcpelauncher/build

      - name: Compilar Trinity Launcher
        run: |
          export CC=clang CXX=clang++
          cmake -S trinity -B trinity/build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -Wno-dev
          ninja -C trinity/build

      - name: Preparar AppDir y Empaquetar con LinuxDeploy
        env:
          ARCH: x86_64
          QMAKE: /usr/lib/qt5/bin/qmake
        run: |
          wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
          wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x linuxdeploy*.AppImage

          mkdir -p AppDir/usr/bin
          mkdir -p AppDir/usr/share/mcpelauncher
          wget -O AppDir/usr/bin/mcpelauncher-client86 https://github.com/javiercplus/my-dockers-setup/releases/download/unstable/mcpelauncher-cli-32bit.AppImage
          chmod +x AppDir/usr/bin/mcpelauncher-client86
          cp mcpelauncher/build/mcpelauncher-client/mcpelauncher-client AppDir/usr/bin/
          cp mcpe-extract/build/mcpelauncher-extract AppDir/usr/bin/
          
          # Copia del binario de Trinity Launcher
          cp trinity/build/app/trinity AppDir/usr/bin/ || cp trinity/build/trinity AppDir/usr/bin/
          
          find msa/build -type f -name "msa-daemon" -exec cp {} AppDir/usr/bin/ \;
          find msa/build -type f -name "msa-ui-qt" -exec cp {} AppDir/usr/bin/ \;
          cp -r linux-bin/* AppDir/usr/share/mcpelauncher/

          # Descarga, extracción y ubicación del entorno de 32 bits
          wget https://huggingface.co/datasets/ccoffee20/PEPE/resolve/main/mcpe32bit.tar
          tar -xf mcpe32bit.tar
          cp 32bitmcpe/bin/mcpelauncher-client86 AppDir/usr/bin/
          mkdir -p AppDir/usr/lib32
          cp -a 32bitmcpe/lib32/* AppDir/usr/lib32/
          
          mkdir -p AppDir/usr/lib
          wget https://huggingface.co/datasets/ccoffee20/PEPE/resolve/main/libevdev.so.2 -O AppDir/usr/lib/libevdev.so.2
          
          LIBZIP_SRC=$(ls /usr/lib/x86_64-linux-gnu/libzip.so.* | head -n 1)
          echo "Copiando libzip desde: $LIBZIP_SRC"
          cp "$LIBZIP_SRC" AppDir/usr/lib/libzip.so.5
          
          cp /usr/lib/x86_64-linux-gnu/libminizip.so.* AppDir/usr/lib/ 2>/dev/null || true

          ./linuxdeploy-x86_64.AppImage --appimage-extract-and-run \
            --appdir AppDir \
            -e AppDir/usr/bin/trinity \
            -d trinity/resources/shortcuts/com.trench.trinity.launcher.desktop \
            -i trinity/resources/branding/com.trench.trinity.launcher.svg \
            --plugin qt \
            --output appimage
          mv  Trinity_Launcher-x86_64.AppImage  Trinity_Launcher-x86_64-LEGACY.AppImage
      - name: Subir AppImage
        uses: actions/upload-artifact@v4
        with:
          name: Trinity-Launcher-Final
          path: "*.AppImage"
      - name: Subir a Release 2.6-beta
        uses: softprops/action-gh-release@v2
        with:
          tag_name: 2.6-beta
          files: |
            Trinity_Launcher-x86_64-LEGACY.AppImage
            *.zsync
